//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienCshape
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLSVEntities : DbContext
    {
        public QLSVEntities()
            : base("name=QLSVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<taikhoan> taikhoan { get; set; }
        public virtual DbSet<tblDiem> tblDiem { get; set; }
        public virtual DbSet<tblDiemTrungBinh> tblDiemTrungBinh { get; set; }
        public virtual DbSet<tblGiaoVien> tblGiaoVien { get; set; }
        public virtual DbSet<tblKhoa> tblKhoa { get; set; }
        public virtual DbSet<tblLopHoc> tblLopHoc { get; set; }
        public virtual DbSet<tblLopHocPhan> tblLopHocPhan { get; set; }
        public virtual DbSet<tblMonHoc> tblMonHoc { get; set; }
        public virtual DbSet<tblPhongDaoTao> tblPhongDaoTao { get; set; }
        public virtual DbSet<tblSinhVien> tblSinhVien { get; set; }
    }
}
