//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienCshape
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiemTrungBinh
    {
        public string masinhvien { get; set; }
        public string hoten { get; set; }
        public string nsinh { get; set; }
        public string gioitinh { get; set; }
        public string lophoc { get; set; }
        public string makhoa { get; set; }
        public Nullable<double> diemtrungbinh { get; set; }
    
        public virtual tblSinhVien tblSinhVien { get; set; }
    }
}
