//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienCshape
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiem
    {
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public string nguoicapnhat { get; set; }
        public string masinhvien { get; set; }
        public string malophocphan { get; set; }
        public Nullable<double> diemchuyencan { get; set; }
        public Nullable<double> diemheso1 { get; set; }
        public Nullable<double> diemheso2_1 { get; set; }
        public Nullable<double> diemheso2_2 { get; set; }
        public Nullable<double> diemquatrinh { get; set; }
        public Nullable<double> diemthi { get; set; }
        public Nullable<double> diemhocphan { get; set; }
    
        public virtual tblSinhVien tblSinhVien { get; set; }
        public virtual tblLopHocPhan tblLopHocPhan { get; set; }
    }
}
