//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienCshape
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLopHocPhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLopHocPhan()
        {
            this.tblDiem = new HashSet<tblDiem>();
        }
    
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public string nguoicapnhat { get; set; }
        public string malophocphan { get; set; }
        public string mamonhoc { get; set; }
        public string magiaovien { get; set; }
        public Nullable<int> hocky { get; set; }
        public Nullable<int> nam { get; set; }
        public string makhoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDiem> tblDiem { get; set; }
        public virtual tblGiaoVien tblGiaoVien { get; set; }
        public virtual tblKhoa tblKhoa { get; set; }
        public virtual tblMonHoc tblMonHoc { get; set; }
    }
}
