//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienCshape
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhongDaoTao
    {
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public string nguoicapnhat { get; set; }
        public string manhanvien { get; set; }
        public string matkhau { get; set; }
        public string ho { get; set; }
        public string tendem { get; set; }
        public string ten { get; set; }
        public Nullable<byte> gioitinh { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string dienthoai { get; set; }
        public string email { get; set; }
        public string diachi { get; set; }
    }
}
