//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienCshape
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSinhVien()
        {
            this.tblDiem = new HashSet<tblDiem>();
        }
    
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string nguoicapnhat { get; set; }
        public string nguoitao { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public string masinhvien { get; set; }
        public string matkhau { get; set; }
        public string ho { get; set; }
        public string tendem { get; set; }
        public string ten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public Nullable<byte> gioitinh { get; set; }
        public string quequan { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public string email { get; set; }
        public string malophoc { get; set; }
        public string hocbong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDiem> tblDiem { get; set; }
        public virtual tblDiemTrungBinh tblDiemTrungBinh { get; set; }
        public virtual tblLopHoc tblLopHoc { get; set; }
    }
}
